# Generated by Django 3.2.12 on 2022-03-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
